=== ziss05/ExtendedTCSC/src/main/resources/TCP.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tree">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="1" name="node" type="Node" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Node" abstract="true" />

    <xs:complexType name="constructor">
        <xs:complexContent>
            <xs:extension base="Node">
                <xs:sequence>
                    <xs:element name="left" type="Node"></xs:element>
                    <xs:element name="right" type="Node"></xs:element>
                </xs:sequence>
                <xs:attribute name="type" type="type" use="required">
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SEQ"/>
            <xs:enumeration value="AND"/>
            <xs:enumeration value="SYNCAND"/>
            <xs:enumeration value="XORC"/>
            <xs:enumeration value="XORD"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="basicService">
        <xs:complexContent>
            <xs:extension base="Node">
                <xs:sequence>
                    <xs:element name="quadruple" type="quadruple" maxOccurs="unbounded">
                    </xs:element>
                </xs:sequence>
                <xs:attribute name="identifier" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="quadruple">
        <xs:sequence maxOccurs="1">
            <xs:element name="d1" type="positiveDec"/>
            <xs:element name="c1" type="positiveDec"/>
            <xs:element name="d2" type="positiveDec"/>
            <xs:element name="c2" type="positiveDec"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="positiveDec">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>


</xs:schema>

=== ziss05/ExtendedTCSC/src/main/resources/AND/10/98.xml
<?xml version="1.0" encoding="UTF-8" ?>

<tree xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../TCP.xsd">
<node xsi:type="constructor" type="AND">
<left xsi:type="basicService" identifier="195">
<quadruple>
<d1>3</d1>
<c1>110</c1>
<d2>5</d2>
<c2>46</c2>
</quadruple>
<quadruple>
<d1>5</d1>
<c1>79</c1>
<d2>18</d2>
<c2>106</c2>
</quadruple>
<quadruple>
<d1>18</d1>
<c1>135</c1>
<d2>31</d2>
<c2>151</c2>
</quadruple>
<quadruple>
<d1>31</d1>
<c1>73</c1>
<d2>42</d2>
<c2>14</c2>
</quadruple>
<quadruple>
<d1>42</d1>
<c1>63</c1>
<d2>53</d2>
<c2>126</c2>
</quadruple>
<quadruple>
<d1>53</d1>
<c1>56</c1>
<d2>61</d2>
<c2>81</c2>
</quadruple>
<quadruple>
<d1>61</d1>
<c1>142</c1>
<d2>74</d2>
<c2>47</c2>
</quadruple>
<quadruple>
<d1>74</d1>
<c1>143</c1>
<d2>75</d2>
<c2>152</c2>
</quadruple>
<quadruple>
<d1>75</d1>
<c1>26</c1>
<d2>87</d2>
<c2>21</c2>
</quadruple>
<quadruple>
<d1>87</d1>
<c1>13</c1>
<d2>152</d2>
<c2>4</c2>
</quadruple>
</left>
<right xsi:type="basicService" identifier="196">
<quadruple>
<d1>3</d1>
<c1>109</c1>
<d2>12</d2>
<c2>88</c2>
</quadruple>
<quadruple>
<d1>12</d1>
<c1>90</c1>
<d2>13</d2>
<c2>21</c2>
</quadruple>
<quadruple>
<d1>13</d1>
<c1>151</c1>
<d2>18</d2>
<c2>15</c2>
</quadruple>
<quadruple>
<d1>18</d1>
<c1>86</c1>
<d2>20</d2>
<c2>63</c2>
</quadruple>
<quadruple>
<d1>20</d1>
<c1>55</c1>
<d2>27</d2>
<c2>124</c2>
</quadruple>
<quadruple>
<d1>27</d1>
<c1>21</c1>
<d2>33</d2>
<c2>124</c2>
</quadruple>
<quadruple>
<d1>33</d1>
<c1>64</c1>
<d2>44</d2>
<c2>88</c2>
</quadruple>
<quadruple>
<d1>44</d1>
<c1>39</c1>
<d2>52</d2>
<c2>112</c2>
</quadruple>
<quadruple>
<d1>52</d1>
<c1>15</c1>
<d2>56</d2>
<c2>58</c2>
</quadruple>
<quadruple>
<d1>56</d1>
<c1>124</c1>
<d2>152</d2>
<c2>101</c2>
</quadruple>
</right>
</node>
</tree>

=== ziss05/ExtendedTCSC/src/main/resources/Tree/25/33.xml
<?xml version="1.0" encoding="UTF-8" ?>

<tree xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../TCP.xsd">
<node xsi:type="constructor" type="AND">
<left xsi:type="constructor" type="XORD">
<left xsi:type="constructor" type="XORC">
<left xsi:type="constructor" type="XORD">
<left xsi:type="constructor" type="XORD">
<left xsi:type="constructor" type="XORC">
<left xsi:type="basicService" identifier="417">
<quadruple>
<d1>25</d1>
<c1>326</c1>
<d2>115</d2>
<c2>201</c2>
</quadruple>
<quadruple>
<d1>115</d1>
<c1>53</c1>
<d2>186</d2>
<c2>160</c2>
</quadruple>
<quadruple>
<d1>186</d1>
<c1>59</c1>
<d2>291</d2>
<c2>184</c2>
</quadruple>
<quadruple>
<d1>291</d1>
<c1>30</c1>
<d2>292</d2>
<c2>58</c2>
</quadruple>
<quadruple>
<d1>292</d1>
<c1>427</c1>
<d2>629</d2>
<c2>560</c2>
</quadruple>
</left>
<right xsi:type="basicService" identifier="418">
<quadruple>
<d1>25</d1>
<c1>61</c1>
<d2>107</d2>
<c2>581</c2>
</quadruple>
<quadruple>
<d1>107</d1>
<c1>126</c1>
<d2>160</d2>
<c2>614</c2>
</quadruple>
<quadruple>
<d1>160</d1>
<c1>577</c1>
<d2>196</d2>
<c2>651</c2>
</quadruple>
<quadruple>
<d1>196</d1>
<c1>321</c1>
<d2>299</d2>
<c2>413</c2>
</quadruple>
<quadruple>
<d1>299</d1>
<c1>478</c1>
<d2>629</d2>
<c2>255</c2>
</quadruple>
</right>
</left>
<right xsi:type="constructor" type="SYNCAND">
<left xsi:type="constructor" type="XORD">
<left xsi:type="basicService" identifier="419">
<quadruple>
<d1>25</d1>
<c1>460</c1>
<d2>132</d2>
<c2>454</c2>
</quadruple>
<quadruple>
<d1>132</d1>
<c1>280</c1>
<d2>227</d2>
<c2>489</c2>
</quadruple>
<quadruple>
<d1>227</d1>
<c1>215</c1>
<d2>289</d2>
<c2>556</c2>
</quadruple>
<quadruple>
<d1>289</d1>
<c1>569</c1>
<d2>395</d2>
<c2>271</c2>
</quadruple>
<quadruple>
<d1>395</d1>
<c1>104</c1>
<d2>629</d2>
<c2>460</c2>
</quadruple>
</left>
<right xsi:type="basicService" identifier="420">
<quadruple>
<d1>25</d1>
<c1>619</c1>
<d2>60</d2>
<c2>142</c2>
</quadruple>
<quadruple>
<d1>60</d1>
<c1>323</c1>
<d2>128</d2>
<c2>245</c2>
</quadruple>
<quadruple>
<d1>128</d1>
<c1>460</c1>
<d2>222</d2>
<c2>587</c2>
</quadruple>
<quadruple>
<d1>222</d1>
<c1>577</c1>
<d2>235</d2>
<c2>541</c2>
</quadruple>
<quadruple>
<d1>235</d1>
<c1>152</c1>
<d2>629</d2>
<c2>146</c2>
</quadruple>
</right>
</left>
<right xsi:type="basicService" identifier="421">
<quadruple>
<d1>25</d1>
<c1>190</c1>
<d2>32</d2>
<c2>369</c2>
</quadruple>
<quadruple>
<d1>32</d1>
<c1>282</c1>
<d2>51</d2>
<c2>570</c2>
</quadruple>
<quadruple>
<d1>51</d1>
<c1>587</c1>
<d2>91</d2>
<c2>303</c2>
</quadruple>
<quadruple>
<d1>91</d1>
<c1>101</c1>
<d2>101</d2>
<c2>507</c2>
</quadruple>
<quadruple>
<d1>101</d1>
<c1>107</c1>
<d2>629</d2>
<c2>365</c2>
</quadruple>
</right>
</right>
</left>
<right xsi:type="constructor" type="XORD">
<left xsi:type="basicService" identifier="422">
<quadruple>
<d1>25</d1>
<c1>461</c1>
<d2>115</d2>
<c2>167</c2>
</quadruple>
<quadruple>
<d1>115</d1>
<c1>167</c1>
<d2>189</d2>
<c2>377</c2>
</quadruple>
<quadruple>
<d1>189</d1>
<c1>500</c1>
<d2>261</d2>
<c2>561</c2>
</quadruple>
<quadruple>
<d1>261</d1>
<c1>59</c1>
<d2>329</d2>
<c2>270</c2>
</quadruple>
<quadruple>
<d1>329</d1>
<c1>297</c1>
<d2>629</d2>
<c2>394</c2>
</quadruple>
</left>
<right xsi:type="basicService" identifier="423">
<quadruple>
<d1>25</d1>
<c1>497</c1>
<d2>83</d2>
<c2>411</c2>
</quadruple>
<quadruple>
<d1>83</d1>
<c1>247</c1>
<d2>151</d2>
<c2>376</c2>
</quadruple>
<quadruple>
<d1>151</d1>
<c1>135</c1>
<d2>167</d2>
<c2>321</c2>
</quadruple>
<quadruple>
<d1>167</d1>
<c1>591</c1>
<d2>284</d2>
<c2>601</c2>
</quadruple>
<quadruple>
<d1>284</d1>
<c1>553</c1>
<d2>629</d2>
<c2>484</c2>
</quadruple>
</right>
</right>
</left>
<right xsi:type="basicService" identifier="424">
<quadruple>
<d1>25</d1>
<c1>320</c1>
<d2>105</d2>
<c2>591</c2>
</quadruple>
<quadruple>
<d1>105</d1>
<c1>240</c1>
<d2>145</d2>
<c2>234</c2>
</quadruple>
<quadruple>
<d1>145</d1>
<c1>636</c1>
<d2>247</d2>
<c2>312</c2>
</quadruple>
<quadruple>
<d1>247</d1>
<c1>149</c1>
<d2>315</d2>
<c2>612</c2>
</quadruple>
<quadruple>
<d1>315</d1>
<c1>216</c1>
<d2>629</d2>
<c2>67</c2>
</quadruple>
</right>
</left>
<right xsi:type="constructor" type="AND">
<left xsi:type="basicService" identifier="425">
<quadruple>
<d1>25</d1>
<c1>159</c1>
<d2>63</d2>
<c2>59</c2>
</quadruple>
<quadruple>
<d1>63</d1>
<c1>223</c1>
<d2>85</d2>
<c2>204</c2>
</quadruple>
<quadruple>
<d1>85</d1>
<c1>157</c1>
<d2>123</d2>
<c2>161</c2>
</quadruple>
<quadruple>
<d1>123</d1>
<c1>187</c1>
<d2>126</d2>
<c2>117</c2>
</quadruple>
<quadruple>
<d1>126</d1>
<c1>298</c1>
<d2>314</d2>
<c2>195</c2>
</quadruple>
</left>
<right xsi:type="basicService" identifier="426">
<quadruple>
<d1>25</d1>
<c1>57</c1>
<d2>78</d2>
<c2>333</c2>
</quadruple>
<quadruple>
<d1>78</d1>
<c1>163</c1>
<d2>135</d2>
<c2>151</c2>
</quadruple>
<quadruple>
<d1>135</d1>
<c1>316</c1>
<d2>184</d2>
<c2>265</c2>
</quadruple>
<quadruple>
<d1>184</d1>
<c1>47</c1>
<d2>185</d2>
<c2>198</c2>
</quadruple>
<quadruple>
<d1>185</d1>
<c1>86</c1>
<d2>314</d2>
<c2>185</c2>
</quadruple>
</right>
</right>
</left>
<right xsi:type="constructor" type="SEQ">
<left xsi:type="constructor" type="AND">
<left xsi:type="basicService" identifier="427">
<quadruple>
<d1>18</d1>
<c1>77</c1>
<d2>61</d2>
<c2>125</c2>
</quadruple>
<quadruple>
<d1>61</d1>
<c1>179</c1>
<d2>95</d2>
<c2>79</c2>
</quadruple>
<quadruple>
<d1>95</d1>
<c1>55</c1>
<d2>104</d2>
<c2>199</c2>
</quadruple>
<quadruple>
<d1>104</d1>
<c1>82</c1>
<d2>134</d2>
<c2>88</c2>
</quadruple>
<quadruple>
<d1>134</d1>
<c1>131</c1>
<d2>235</d2>
<c2>67</c2>
</quadruple>
</left>
<right xsi:type="basicService" identifier="428">
<quadruple>
<d1>18</d1>
<c1>83</c1>
<d2>56</d2>
<c2>47</c2>
</quadruple>
<quadruple>
<d1>56</d1>
<c1>193</c1>
<d2>87</d2>
<c2>190</c2>
</quadruple>
<quadruple>
<d1>87</d1>
<c1>232</c1>
<d2>122</d2>
<c2>84</c2>
</quadruple>
<quadruple>
<d1>122</d1>
<c1>121</c1>
<d2>141</d2>
<c2>174</c2>
</quadruple>
<quadruple>
<d1>141</d1>
<c1>156</c1>
<d2>235</d2>
<c2>239</c2>
</quadruple>
</right>
</left>
<right xsi:type="basicService" identifier="429">
<quadruple>
<d1>6</d1>
<c1>21</c1>
<d2>19</d2>
<c2>127</c2>
</quadruple>
<quadruple>
<d1>19</d1>
<c1>97</c1>
<d2>32</d2>
<c2>24</c2>
</quadruple>
<quadruple>
<d1>32</d1>
<c1>129</c1>
<d2>56</d2>
<c2>96</c2>
</quadruple>
<quadruple>
<d1>56</d1>
<c1>123</c1>
<d2>70</d2>
<c2>97</c2>
</quadruple>
<quadruple>
<d1>70</d1>
<c1>111</c1>
<d2>157</d2>
<c2>66</c2>
</quadruple>
</right>
</right>
</node>
</tree>
